import './globals.css'
import 'react-toastify/dist/ReactToastify.css';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import jwt from "jsonwebtoken";
import ActiveUserProvider from '@/context/ActiveUserContext';
import { cookies } from 'next/headers';

export const metadata = {
  title: 'Dream Shop',
  description: 'Generated by Dilwala Shakib',
}

const getUserInfo = async() => {
  const cookie = await cookies();
  const info = cookie.get("userInfo");
  if(info?.value) {
    const userInfo = jwt.verify(info.value, process.env.TOKEN_SECRET_KEY);
    return userInfo
  }
}

export default async function RootLayout({ children }) {
  const userInfo = await getUserInfo();  
  return (
    <html lang="en">
      <body>
        {/* suppressHydrationWarning={true} */}
        <ActiveUserProvider userInfo={userInfo}>
          {children}
        </ActiveUserProvider>
      </body>
    </html>
  )
}
